<#
.SYNOPSIS
    Creates a local zip of the report and evidence generated by one SAP test run,
    and uploads it to Azure Blob Storage when a connection string is configured.

.DESCRIPTION
    Collects the current Playwright HTML report, run result files, dashboard and
    evidence images changed during the run, then writes one zip to the user's
    Downloads folder unless an explicit output folder is supplied.

    If AZURE_STORAGE_CONNECTION_STRING is set in the environment (this
    workspace keeps it in the gitignored .claude/settings.local.json, the same
    place SAP_DS4_100_NIIF_PASSWORD lives), the zip is also uploaded to the
    'sap-test-archives' container under a blob path derived from the local
    archive folder name, so evidence backs up off the tester's machine without
    a person doing it by hand. A missing connection string, or an upload
    failure, is a warning, not an error - the local zip is the record of
    record and this script must not fail a run over network trouble.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $RunId,

    [Parameter(Mandatory = $true)]
    [datetime] $StartedAtUtc,

    [string] $Case = '',
    [ValidateSet('web', 'gui')]
    [string] $Lane = 'web',
    [string] $SystemId = '',
    [string] $OutputRoot = ''
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$resultsRoot = Join-Path $root 'results'
$evidenceRoot = Join-Path $root 'evidence'
if (-not $OutputRoot) { $OutputRoot = $env:FSNXT_ARTIFACT_ARCHIVE_DIR }
if (-not $OutputRoot) {
    $downloads = if ($env:USERPROFILE) { Join-Path $env:USERPROFILE 'Downloads' } else { $resultsRoot }
    $OutputRoot = Join-Path $downloads 'FSNXT SAP Test Archives'
}
$archiveRoot = $OutputRoot
$safeCase = if ($Case) { $Case -replace '[^A-Za-z0-9_-]', '-' } else { 'sap-run' }
$safeLane = $Lane -replace '[^A-Za-z0-9_-]', '-'
$zipName = "{0}-{1}-{2}.zip" -f $RunId, $safeCase, $safeLane
$zipPath = Join-Path $archiveRoot $zipName
$stageRoot = Join-Path ([IO.Path]::GetTempPath()) "fsnxt-sap-artifacts-$RunId"

function Add-RelativeFile {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path
    )
    if (-not $Path -or -not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
    $full = [IO.Path]::GetFullPath($Path)
    if (-not $Files.Contains($full)) { $Files.Add($full) | Out-Null }
}

function Add-RecentFiles {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path,
        [string[]] $Include
    )
    if (-not (Test-Path -LiteralPath $Path)) { return }
    Get-ChildItem -LiteralPath $Path -Recurse -File -Include $Include -ErrorAction SilentlyContinue |
        Where-Object { $_.LastWriteTimeUtc -ge $StartedAtUtc } |
        ForEach-Object { Add-RelativeFile -Files $Files -Path $_.FullName }
}

function Add-DirectoryFiles {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path
    )
    if (-not (Test-Path -LiteralPath $Path)) { return }
    Get-ChildItem -LiteralPath $Path -Recurse -File -ErrorAction SilentlyContinue |
        ForEach-Object { Add-RelativeFile -Files $Files -Path $_.FullName }
}

function Copy-IntoStage {
    param([string] $Source)
    $rootUri = [Uri](([IO.Path]::GetFullPath($root).TrimEnd('\') + '\'))
    $sourceUri = [Uri]([IO.Path]::GetFullPath($Source))
    $relative = [Uri]::UnescapeDataString($rootUri.MakeRelativeUri($sourceUri).ToString()).Replace('/', '\')
    if ($relative.StartsWith('..')) {
        $relative = Join-Path 'external' ([IO.Path]::GetFileName($Source))
    }
    $destination = Join-Path $stageRoot $relative
    $destinationDir = Split-Path -Parent $destination
    New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
    Copy-Item -LiteralPath $Source -Destination $destination -Force
}

function Get-AzureBlobContext {
    param([string] $ConnectionString)
    $parts = @{}
    foreach ($piece in ($ConnectionString -split ';')) {
        if (-not $piece) { continue }
        $kv = $piece -split '=', 2
        if ($kv.Count -eq 2) { $parts[$kv[0]] = $kv[1] }
    }
    if (-not $parts.AccountName -or -not $parts.AccountKey) {
        throw 'AZURE_STORAGE_CONNECTION_STRING is missing AccountName or AccountKey.'
    }
    $suffix = if ($parts.EndpointSuffix) { $parts.EndpointSuffix } else { 'core.windows.net' }
    $protocol = if ($parts.DefaultEndpointsProtocol) { $parts.DefaultEndpointsProtocol } else { 'https' }
    [PSCustomObject]@{
        AccountName  = $parts.AccountName
        AccountKey   = $parts.AccountKey
        BlobEndpoint = "{0}://{1}.blob.{2}" -f $protocol, $parts.AccountName, $suffix
    }
}

# Azure Storage Shared Key authorization for Put Blob / Put Container - see
# https://learn.microsoft.com/rest/api/storageservices/authorize-with-shared-key
function New-AzureBlobAuthHeader {
    param(
        [Parameter(Mandatory = $true)] $Context,
        [Parameter(Mandatory = $true)] [string] $CanonicalizedResource,
        [Parameter(Mandatory = $true)] [hashtable] $MsHeaders,
        [string] $ContentLength = '',
        [string] $ContentType = ''
    )
    $canonicalizedHeaders = ($MsHeaders.GetEnumerator() | Sort-Object Name | ForEach-Object { "$($_.Name):$($_.Value)" }) -join "`n"
    $stringToSign = (
        'PUT', '', '', $ContentLength, '', $ContentType, '', '', '', '', '', ''
    ) -join "`n"
    $stringToSign = "$stringToSign`n$canonicalizedHeaders`n$CanonicalizedResource"

    $hmac = New-Object System.Security.Cryptography.HMACSHA256
    $hmac.Key = [Convert]::FromBase64String($Context.AccountKey)
    $signature = [Convert]::ToBase64String($hmac.ComputeHash([Text.Encoding]::UTF8.GetBytes($stringToSign)))
    return "SharedKey $($Context.AccountName):$signature"
}

function Assert-AzureBlobContainer {
    param($Context, [string] $Container)
    $date = [DateTime]::UtcNow.ToString('R')
    $msHeaders = @{ 'x-ms-date' = $date; 'x-ms-version' = '2021-08-06' }
    $resource = "/$($Context.AccountName)/$Container`nrestype:container"
    $auth = New-AzureBlobAuthHeader -Context $Context -CanonicalizedResource $resource -MsHeaders $msHeaders
    try {
        Invoke-WebRequest -Uri "$($Context.BlobEndpoint)/$Container`?restype=container" -Method Put -Headers @{
            'x-ms-date'     = $date
            'x-ms-version'  = '2021-08-06'
            'Authorization' = $auth
        } -UseBasicParsing | Out-Null
    } catch {
        $status = $_.Exception.Response.StatusCode.value__
        if ($status -ne 409) { throw }
    }
}

function Send-AzureBlobFile {
    param($Context, [string] $Container, [string] $BlobPath, [string] $FilePath)
    Assert-AzureBlobContainer -Context $Context -Container $Container
    $bytes = [IO.File]::ReadAllBytes($FilePath)
    $date = [DateTime]::UtcNow.ToString('R')
    $msHeaders = @{ 'x-ms-date' = $date; 'x-ms-version' = '2021-08-06'; 'x-ms-blob-type' = 'BlockBlob' }
    $resource = "/$($Context.AccountName)/$Container/$BlobPath"
    $auth = New-AzureBlobAuthHeader -Context $Context -CanonicalizedResource $resource -MsHeaders $msHeaders `
        -ContentLength $bytes.Length -ContentType 'application/zip'
    Invoke-WebRequest -Uri "$($Context.BlobEndpoint)/$Container/$BlobPath" -Method Put -Headers @{
        'x-ms-date'      = $date
        'x-ms-version'   = '2021-08-06'
        'x-ms-blob-type' = 'BlockBlob'
        'Authorization'  = $auth
        'Content-Type'   = 'application/zip'
    } -Body $bytes -UseBasicParsing | Out-Null
}

if (Test-Path -LiteralPath $stageRoot) {
    Remove-Item -LiteralPath $stageRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $stageRoot -Force | Out-Null
New-Item -ItemType Directory -Path $archiveRoot -Force | Out-Null

$files = [System.Collections.Generic.List[string]]::new()

Add-RecentFiles -Files $files -Path $resultsRoot -Include @('TC-*.md', '*.json', '*.ndjson', '*.txt')
Add-RecentFiles -Files $files -Path $evidenceRoot -Include @('*.png', '*.jpg', '*.jpeg')
Add-RelativeFile -Files $files -Path (Join-Path $resultsRoot 'dashboard.html')

if ($Lane -eq 'web') {
    Add-DirectoryFiles -Files $files -Path (Join-Path $resultsRoot 'web\html-report')
    Add-RecentFiles -Files $files -Path (Join-Path $resultsRoot 'web\test-output') -Include @('*.png', '*.webm', '*.zip', '*.trace', '*.txt', '*.json')
}

if ($Lane -eq 'gui' -and $SystemId) {
    Add-RecentFiles -Files $files -Path (Join-Path $resultsRoot "gui\$SystemId") -Include @('*.ndjson', '*.json', '*.txt')
}

$files = @($files | Sort-Object -Unique)
if ($files.Count -eq 0) {
    Write-Host 'No report or evidence files were found to archive.' -ForegroundColor Yellow
    exit 0
}

foreach ($file in $files) {
    Copy-IntoStage -Source $file
}

if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}

Compress-Archive -Path (Join-Path $stageRoot '*') -DestinationPath $zipPath -CompressionLevel Optimal -Force
Remove-Item -LiteralPath $stageRoot -Recurse -Force

Write-Host ("Artifact archive  {0}" -f $zipPath) -ForegroundColor Green

if ($env:AZURE_STORAGE_CONNECTION_STRING) {
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        $azureContext = Get-AzureBlobContext -ConnectionString $env:AZURE_STORAGE_CONNECTION_STRING
        $blobFolder = (Split-Path -Leaf $archiveRoot) -replace '[^A-Za-z0-9_-]', '-'
        $blobPath = "$blobFolder/$zipName"
        Send-AzureBlobFile -Context $azureContext -Container 'sap-test-archives' -BlobPath $blobPath -FilePath $zipPath
        Write-Host ("Uploaded to Azure Blob  sap-test-archives/{0}" -f $blobPath) -ForegroundColor Green
    } catch {
        Write-Host ("Azure Blob upload failed - the local zip is still on disk: {0}" -f $_.Exception.Message) -ForegroundColor Yellow
    }
} else {
    Write-Host 'AZURE_STORAGE_CONNECTION_STRING is not set - skipping the Azure Blob upload.' -ForegroundColor DarkGray
}
