<#
.SYNOPSIS
    Creates a local zip of the report and evidence generated by one SAP test run.

.DESCRIPTION
    This is the local handoff point for future blob upload. It collects the
    current Playwright HTML report, run result files, dashboard and evidence
    images changed during the run, then writes one zip to the user's Downloads
    folder unless an explicit output folder is supplied.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $RunId,

    [Parameter(Mandatory = $true)]
    [datetime] $StartedAtUtc,

    [string] $Case = '',
    [ValidateSet('web', 'gui')]
    [string] $Lane = 'web',
    [string] $SystemId = '',
    [string] $OutputRoot = ''
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$resultsRoot = Join-Path $root 'results'
$evidenceRoot = Join-Path $root 'evidence'
if (-not $OutputRoot) { $OutputRoot = $env:FSNXT_ARTIFACT_ARCHIVE_DIR }
if (-not $OutputRoot) {
    $downloads = if ($env:USERPROFILE) { Join-Path $env:USERPROFILE 'Downloads' } else { $resultsRoot }
    $OutputRoot = Join-Path $downloads 'FSNXT SAP Test Archives'
}
$archiveRoot = $OutputRoot
$safeCase = if ($Case) { $Case -replace '[^A-Za-z0-9_-]', '-' } else { 'sap-run' }
$safeLane = $Lane -replace '[^A-Za-z0-9_-]', '-'
$zipName = "{0}-{1}-{2}.zip" -f $RunId, $safeCase, $safeLane
$zipPath = Join-Path $archiveRoot $zipName
$stageRoot = Join-Path ([IO.Path]::GetTempPath()) "fsnxt-sap-artifacts-$RunId"

function Add-RelativeFile {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path
    )
    if (-not $Path -or -not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
    $full = [IO.Path]::GetFullPath($Path)
    if (-not $Files.Contains($full)) { $Files.Add($full) | Out-Null }
}

function Add-RecentFiles {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path,
        [string[]] $Include
    )
    if (-not (Test-Path -LiteralPath $Path)) { return }
    Get-ChildItem -LiteralPath $Path -Recurse -File -Include $Include -ErrorAction SilentlyContinue |
        Where-Object { $_.LastWriteTimeUtc -ge $StartedAtUtc } |
        ForEach-Object { Add-RelativeFile -Files $Files -Path $_.FullName }
}

function Add-DirectoryFiles {
    param(
        [System.Collections.Generic.List[string]] $Files,
        [string] $Path
    )
    if (-not (Test-Path -LiteralPath $Path)) { return }
    Get-ChildItem -LiteralPath $Path -Recurse -File -ErrorAction SilentlyContinue |
        ForEach-Object { Add-RelativeFile -Files $Files -Path $_.FullName }
}

function Copy-IntoStage {
    param([string] $Source)
    $rootUri = [Uri](([IO.Path]::GetFullPath($root).TrimEnd('\') + '\'))
    $sourceUri = [Uri]([IO.Path]::GetFullPath($Source))
    $relative = [Uri]::UnescapeDataString($rootUri.MakeRelativeUri($sourceUri).ToString()).Replace('/', '\')
    if ($relative.StartsWith('..')) {
        $relative = Join-Path 'external' ([IO.Path]::GetFileName($Source))
    }
    $destination = Join-Path $stageRoot $relative
    $destinationDir = Split-Path -Parent $destination
    New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
    Copy-Item -LiteralPath $Source -Destination $destination -Force
}

if (Test-Path -LiteralPath $stageRoot) {
    Remove-Item -LiteralPath $stageRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $stageRoot -Force | Out-Null
New-Item -ItemType Directory -Path $archiveRoot -Force | Out-Null

$files = [System.Collections.Generic.List[string]]::new()

Add-RecentFiles -Files $files -Path $resultsRoot -Include @('TC-*.md', '*.json', '*.ndjson', '*.txt')
Add-RecentFiles -Files $files -Path $evidenceRoot -Include @('*.png', '*.jpg', '*.jpeg')
Add-RelativeFile -Files $files -Path (Join-Path $resultsRoot 'dashboard.html')

if ($Lane -eq 'web') {
    Add-DirectoryFiles -Files $files -Path (Join-Path $resultsRoot 'web\html-report')
    Add-RecentFiles -Files $files -Path (Join-Path $resultsRoot 'web\test-output') -Include @('*.png', '*.webm', '*.zip', '*.trace', '*.txt', '*.json')
}

if ($Lane -eq 'gui' -and $SystemId) {
    Add-RecentFiles -Files $files -Path (Join-Path $resultsRoot "gui\$SystemId") -Include @('*.ndjson', '*.json', '*.txt')
}

$files = @($files | Sort-Object -Unique)
if ($files.Count -eq 0) {
    Write-Host 'No report or evidence files were found to archive.' -ForegroundColor Yellow
    exit 0
}

foreach ($file in $files) {
    Copy-IntoStage -Source $file
}

if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}

Compress-Archive -Path (Join-Path $stageRoot '*') -DestinationPath $zipPath -CompressionLevel Optimal -Force
Remove-Item -LiteralPath $stageRoot -Recurse -Force

Write-Host ("Artifact archive  {0}" -f $zipPath) -ForegroundColor Green
