"""DOM extraction and interaction helpers: element discovery, selector building,
form filling, and dropdown/toast handling."""
from ai_agents import config

# Visibility check works for position:fixed modal content too (offsetParent is
# null for fixed-position subtrees, which used to hide modal contents from the
# scanner - checkVisibility()/getBoundingClientRect() fixes that).
_EXTRACT_JS = """
(scopeSelector) => {
    function getXPath(el) {
        if (el.id) return `//*[@id="${el.id}"]`;
        const parts = [];
        while (el && el.nodeType === Node.ELEMENT_NODE) {
            let index = 0;
            let sibling = el.previousSibling;
            while (sibling) {
                if (sibling.nodeType === Node.ELEMENT_NODE && sibling.tagName === el.tagName) index++;
                sibling = sibling.previousSibling;
            }
            const tag = el.tagName.toLowerCase();
            parts.unshift(index ? `${tag}[${index + 1}]` : tag);
            el = el.parentElement;
        }
        return "/" + parts.join("/");
    }
    const looksAutoGenerated = (id) => {
        if (!id) return false;
        return /^(mui-|radix-|react-|:r)/.test(id) || /^[a-z0-9]{0,3}-?\\d{3,}$/i.test(id);
    };
    const isVisible = (el) => {
        try {
            if (el.checkVisibility && !el.checkVisibility()) return false;
            const r = el.getBoundingClientRect();
            if (r.width === 0 && r.height === 0) return false;
            const s = getComputedStyle(el);
            return s.display !== 'none' && s.visibility !== 'hidden';
        } catch (e) { return false; }
    };
    // Visible label text associated with a form control, however it's wired up.
    const labelFor = (el) => {
        try {
            if (el.getAttribute("aria-labelledby")) {
                const t = el.getAttribute("aria-labelledby").split(/\\s+/)
                    .map(id => (document.getElementById(id) || {}).innerText || "")
                    .join(" ").trim();
                if (t) return t.slice(0, 80);
            }
            if (el.id) {
                const l = document.querySelector(`label[for="${el.id}"]`);
                if (l && l.innerText.trim()) return l.innerText.trim().slice(0, 80);
            }
            const closest = el.closest("label");
            if (closest && closest.innerText.trim()) return closest.innerText.trim().slice(0, 80);
            // Common pattern: the label sits immediately before the field. Only for
            // real form fields - a button's previous sibling is not its label.
            if (/^(input|select|textarea)$/i.test(el.tagName)) {
                const prev = el.previousElementSibling;
                if (prev && /^(label|span|div|p)$/i.test(prev.tagName)) {
                    const t = (prev.innerText || "").trim();
                    if (t && t.length < 60) return t.slice(0, 80);
                }
            }
        } catch (e) {}
        return null;
    };
    // Two DIFFERENT problems, deliberately kept apart:
    //   inert   -> the app switched this control off (disabled / no pointer events)
    //   covered -> the control is fine, but something is painted on top of it
    // They need different wording in the report, so don't collapse them.
    const clickability = (el, s, r) => {
        const out = {inert: false, reason: null, covered_by: null};
        if (el.disabled || el.getAttribute("aria-disabled") === "true") {
            out.inert = true; out.reason = "switched off"; return out;
        }
        if (s.pointerEvents === "none") { out.inert = true; out.reason = "ignores clicks"; return out; }
        if (r.width < 1 || r.height < 1) { out.inert = true; out.reason = "no size on screen"; return out; }
        try {
            const cx = r.left + r.width / 2, cy = r.top + r.height / 2;
            if (cx >= 0 && cy >= 0 && cx <= innerWidth && cy <= innerHeight) {
                // elementFromPoint already ignores pointer-events:none layers, so
                // anything it returns really would intercept the click.
                const top = document.elementFromPoint(cx, cy);
                if (top && top !== el && !el.contains(top) && !top.contains(el)) {
                    out.covered_by = top.tagName.toLowerCase() +
                        (top.className && typeof top.className === "string" && top.className.trim()
                            ? "." + top.className.trim().split(/\\s+/)[0] : "");
                }
            }
        } catch (e) {}
        return out;
    };
    const root = scopeSelector ? document.querySelector(scopeSelector) : document;
    if (!root) return [];
    const selector = "button, a, input, select, textarea, [role='button'], [role='tab'], [onclick]";
    const nodes = Array.from(root.querySelectorAll(selector));
    return nodes
        .filter(isVisible)
        .slice(0, 150)
        .map(el => {
            const s = getComputedStyle(el);
            const r = el.getBoundingClientRect();
            const click = clickability(el, s, r);
            return {
            tag: el.tagName.toLowerCase(),
            id: el.id || null,
            id_looks_stable: el.id ? !looksAutoGenerated(el.id) : false,
            name: el.getAttribute("name") || null,
            text: (el.innerText || el.value || "").trim().slice(0, 60) || null,
            placeholder: el.getAttribute("placeholder") || null,
            testId: el.getAttribute("data-testid") || null,
            ariaLabel: el.getAttribute("aria-label") || null,
            title: el.getAttribute("title") || null,
            role: el.getAttribute("role") || null,
            href: el.getAttribute("href") || null,
            type: el.getAttribute("type") || null,
            required: el.hasAttribute("required") || el.getAttribute("aria-required") === "true",
            label: labelFor(el),
            // Native constraint attributes - a senior QA plans boundary cases from these.
            maxlength: el.getAttribute("maxlength") || null,
            minlength: el.getAttribute("minlength") || null,
            min: el.getAttribute("min") || null,
            max: el.getAttribute("max") || null,
            step: el.getAttribute("step") || null,
            pattern: el.getAttribute("pattern") || null,
            inputmode: el.getAttribute("inputmode") || null,
            value: (el.value != null ? String(el.value) : "").slice(0, 80),
            // Interaction state
            is_disabled: click.inert,
            is_readonly: !!el.readOnly || el.hasAttribute('readonly') ||
                         el.getAttribute('aria-readonly') === 'true',
            not_clickable_reason: click.reason,
            is_covered: !!click.covered_by,
            covered_by: click.covered_by,
            looks_enabled: click.inert
                ? (parseFloat(s.opacity) >= 0.9 && s.cursor !== "not-allowed")
                : true,
            cursor: s.cursor,
            width: Math.round(r.width),
            height: Math.round(r.height),
            in_modal: !!el.closest("[role='dialog'], [aria-modal='true'], .modal, dialog, .MuiDialog-root, .ant-modal, .p-dialog, .popup, .ReactModal__Content"),
            xpath: getXPath(el)
        };});
}
"""


def get_page_elements(page, scope_selector=None):
    try:
        return page.evaluate(_EXTRACT_JS, scope_selector)
    except Exception as e:
        print(f"    [dom] extraction failed: {e}")
        return []


def _quote(value):
    """Safe attribute-selector literal: a value containing a quote would
    otherwise produce a selector that silently matches nothing."""
    v = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{v}"'


def build_selector(el):
    """Priority chain; xpath is always available as a guaranteed fallback.
    Never invents selectors - only uses what's actually on the element.

    A `text=` selector is deliberately NOT produced here. Element text is
    innerText, which for a button like "+ Create Facility" (icon span + label
    span) or a dropdown listing every option arrives with embedded newlines and
    is sliced at 60 chars, possibly mid-word. Playwright cannot match that, so
    the click times out and a perfectly working button gets reported broken.
    xpath is unambiguous and always present, so it is the fallback instead.
    """
    if el.get("testId"):
        return f"[data-testid={_quote(el['testId'])}]"
    if el.get("id") and el.get("id_looks_stable"):
        return f"[id={_quote(el['id'])}]"
    if el.get("name"):
        return f"[name={_quote(el['name'])}]"
    if el.get("ariaLabel"):
        return f"[aria-label={_quote(el['ariaLabel'])}]"
    if el.get("title"):
        return f"[title={_quote(el['title'])}]"
    if el.get("placeholder"):
        return f"[placeholder={_quote(el['placeholder'])}]"
    return f"xpath={el['xpath']}"


def _matches_identity(el, probe):
    """Is the element we just resolved the same one we extracted?"""
    if not probe:
        return False
    if probe.get("tag") != el.get("tag"):
        return False
    want = _norm_text(el.get("text"))
    got = _norm_text(probe.get("text"))
    if want and got:
        # Truncation at 60 chars means one may be a prefix of the other.
        return want in got or got in want
    return True


def _norm_text(s):
    return " ".join(str(s or "").split()).lower()


def resolve(page, el, timeout=None):
    """Return a Locator that points at exactly this element, or None.

    Tries each candidate selector in priority order and accepts the first that
    resolves to a UNIQUE element whose identity matches what we extracted. This
    is what stops `.first` from silently clicking a different control that
    happens to share a placeholder or label with the intended one.
    """
    timeout = timeout or 3000
    candidates = []
    primary = build_selector(el)
    candidates.append(primary)
    if el.get("xpath") and not primary.startswith("xpath="):
        candidates.append(f"xpath={el['xpath']}")     # unique by construction

    for sel in candidates:
        try:
            loc = page.locator(sel)
            n = loc.count()
        except Exception:
            continue
        if n == 0:
            continue
        if n == 1:
            return loc.first
        # Ambiguous: disambiguate by identity rather than blindly taking .first.
        for i in range(min(n, 8)):
            cand = loc.nth(i)
            try:
                probe = {
                    "tag": cand.evaluate("e => e.tagName.toLowerCase()", timeout=timeout),
                    "text": cand.evaluate("e => (e.innerText || e.value || '')", timeout=timeout),
                }
            except Exception:
                continue
            if _matches_identity(el, probe):
                return cand
    return None


def element_label(el):
    return (el.get("label") or el.get("text") or el.get("ariaLabel") or el.get("title")
            or el.get("placeholder") or el.get("name") or build_selector(el))


def field_kind(el):
    """Best guess at what a form field actually expects, so test cases can be
    tailored (an email field needs different abuse than an amount field)."""
    t = (el.get("type") or "").lower()
    if t in ("email", "number", "date", "tel", "url", "password", "time",
             "datetime-local", "month", "week", "search", "color", "range"):
        return t
    if el.get("tag") == "select" or is_custom_dropdown_field(el):
        return "dropdown"
    if el.get("tag") == "textarea":
        return "longtext"
    hint = " ".join(str(el.get(k) or "") for k in
                    ("label", "placeholder", "name", "id", "ariaLabel")).lower()
    for needle, kind in (
        ("email", "email"), ("mobile", "tel"), ("phone", "tel"), ("contact", "tel"),
        ("date", "date"), ("expiry", "date"), ("maturity", "date"), ("tenor", "number"),
        ("amount", "number"), ("qty", "number"), ("quantity", "number"),
        ("rate", "number"), ("price", "number"), ("limit", "number"), ("percent", "number"),
        ("pincode", "number"), ("pin code", "number"), ("zip", "number"),
        ("password", "password"), ("url", "url"), ("website", "url"),
        ("pan", "text"), ("gst", "text"), ("ifsc", "text"), ("account", "text"),
    ):
        if needle in hint:
            return kind
    return "text"


def describe_field(el, index):
    """Compact, Claude-friendly description of one fillable field."""
    return {
        "index": index,
        "label": el.get("label") or el.get("ariaLabel") or el.get("placeholder") or el.get("name"),
        "kind": field_kind(el),
        "tag": el.get("tag"),
        "type": el.get("type"),
        "placeholder": el.get("placeholder"),
        "required": bool(el.get("required")),
        "maxlength": el.get("maxlength"),
        "minlength": el.get("minlength"),
        "min": el.get("min"),
        "max": el.get("max"),
        "pattern": el.get("pattern"),
        "current_value": el.get("value") or "",
    }


def is_destructive_element(el):
    blob = " ".join(str(el.get(k) or "") for k in ("text", "ariaLabel", "title", "name", "id"))
    return bool(config.DESTRUCTIVE_RE.search(blob))


def is_custom_dropdown_field(el):
    ph = (el.get("placeholder") or "").lower()
    if "date" in ph:
        return False
    return ph.startswith("select") or el.get("tag") == "select"


def get_dropdown_option_texts(page):
    return page.evaluate("""
    () => {
        const opts = Array.from(document.querySelectorAll(
            "[role='option'], li[role], .option, .dropdown-item, [data-value], ul li"
        ));
        const vis = o => { const r = o.getBoundingClientRect(); return r.width > 0 && r.height > 0; };
        return opts.filter(vis).slice(0, 50).map(o => o.innerText.trim()).filter(t => t.length > 0);
    }
    """)


def select_dropdown_option(page, el, desired_value=None):
    selector = build_selector(el)
    try:
        page.locator(selector).first.click(timeout=config.STEP_TIMEOUT_MS)
    except Exception as e:
        return False, f"Could not open dropdown ({selector}): {e}"
    page.wait_for_timeout(400)
    options = get_dropdown_option_texts(page)
    if not options:
        page.keyboard.press("Escape")
        return False, "Dropdown opened but no options were detected"
    target_text = None
    if desired_value:
        for opt in options:
            if desired_value.lower() in opt.lower():
                target_text = opt
                break
    if not target_text:
        target_text = options[0]
    try:
        page.get_by_text(target_text, exact=True).first.click(timeout=config.STEP_TIMEOUT_MS)
        return True, target_text
    except Exception as e:
        page.keyboard.press("Escape")
        return False, f"Failed clicking option '{target_text}': {e}"


def fill_form_fields(page, elements, field_values):
    """Returns a human-readable fill log."""
    log = []
    for item in field_values:
        idx = item.get("index")
        if idx is None or not (0 <= idx < len(elements)):
            continue
        el = elements[idx]
        value = str(item.get("value", ""))
        selector = build_selector(el)
        try:
            if el.get("tag") == "select":
                page.locator(selector).first.select_option(label=value, timeout=config.STEP_TIMEOUT_MS)
                log.append(f"selected '{value}' in {element_label(el)}")
            elif is_custom_dropdown_field(el):
                if value == "":
                    log.append(f"left dropdown {element_label(el)} empty (intentional)")
                    continue
                ok, detail = select_dropdown_option(page, el, desired_value=value)
                log.append(f"dropdown {element_label(el)}: {'picked ' + detail if ok else 'FAILED - ' + detail}")
            else:
                page.locator(selector).first.fill(value, timeout=config.STEP_TIMEOUT_MS)
                log.append(f"filled {element_label(el)} = '{value}'")
        except Exception as e:
            log.append(f"could not fill {element_label(el)}: {e}")
    return log


def get_toast_or_message_text(page):
    texts = []
    for sel in [".Toastify", "[role='alert']", ".toast", ".error-message", ".validation-error",
                ".invalid-feedback", ".Mui-error", ".ant-form-item-explain-error", "[aria-invalid='true']"]:
        try:
            loc = page.locator(sel)
            n = min(loc.count(), 5)
            for i in range(n):
                t = loc.nth(i).inner_text(timeout=1500).strip()
                if t:
                    texts.append(t)
        except Exception:
            continue
    return " | ".join(dict.fromkeys(texts))  # de-dup, keep order

